#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d "www" "edi" "mus" "fil" "img" "-1-" "-2-" "-3-" 

bspc config border_width          2
bspc config window_gap            7

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

~/.config/autostart.sh &
/usr/bin/dunst -conf ~/.config/dunst/dunstrc &
/usr/bin/polybar -c ~/.config/polybar/config.ini &
