#! /bin/sh

bspc monitor -d "  " "  " "  " "  " "  " " ➊ " " ➋ " " ➌ " 

bspc config border_width          1
bspc config window_gap            5

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

~/.config/autostart.sh &
/usr/bin/dunst -conf ~/.config/dunst/dunstrc &
/usr/bin/polybar -c ~/.config/polybar/config.ini -r &
